version: "3.8"
services:
  node:
    build: "."
    image: eslint-config-dms:local
    volumes:
      - "./package.json:/app/package.json"
      - "./tsconfig.json:/app/tsconfig.json"
      - "./base.js:/app/base.js"
      - "./react.js:/app/react.js"
      - "./src:/app/src"
      - "./scripts:/app/scripts"
